export const DISPLAY_LIST = [
  'unset',
  'revert',
  'initial',
  'inherit',
  'list-item',
  'table-row',
  'table',
  'contents',
  'none',
  'flow-root',
  'inline-grid',
  'grid',
  'inline-flex',
  'flex',
  'inline-block',
  'inline',
  'block',
]

export const JUSTIFY_CONTENT_LIST = [
  'center',
  'start',
  'end',
  'flex-start',
  'flex-end',
  'left',
  'right',
  'space-between',
  'between',
  'space-around',
  'around',
  'space-evenly',
  'evenly',
  'stretch',
  'inherit',
  'initial',
  'unset',
  'normal',
]
export const ALIGN_ITEMS_LIST = [
  'baseline',
  'center',
  'end',
  'flex-end',
  'flex-start',
  'inherit',
  'initial',
  'normal',
  'self-end',
  'self-start',
  'start',
  'stretch',
  'unset',
]

export const CURSOR_LIST = [
  'auto',
  'default',
  'none',
  'context-menu',
  'help',
  'pointer',
  'progress',
  'wait',
  'cell',
  'crosshair',
  'text',
  'vertical-text',
  'alias',
  'copy',
  'move',
  'no-drop',
  'not-allowed',
  'e-resize',
  'n-resize',
  'ne-resize',
  'nw-resize',
  's-resize',
  'se-resize',
  'sw-resize',
  'w-resize',
  'ew-resize',
  'ns-resize',
  'nesw-resize',
  'nwse-resize',
  'col-resize',
  'row-resize',
  'all-scroll',
  'zoom-in',
  'zoom-out',
  'grab',
  'grabbing',
]

export const UNIT_LIST = [
  'cm',
  'mm',
  'in',
  'px',
  'pt',
  'pc',
  'em',
  'ex',
  'ch',
  'rem',
  'vw',
  'vh',
  'vmin',
  'vmax',
  'p',
  '%',
  'v',
  '',
]

export const WHITE_SPACE_LIST = [
  'normal',
  'nowrap',
  'pre',
  'pre-wrap',
  'pre-line',
  'break-spaces',
  'inherit',
  'initial',
  'revert',
  'revert-layer',
  'unset',
]

export const NUM_LIST = [0, 123, 0.25, 3.1415926, 999999999]

export const NumAndUnitList = NUM_LIST.map((num) =>
  UNIT_LIST.map((unit) => `${num}${unit}`)
).flat(Infinity)

export const PSEUDO_LIST = [
  'active',
  'any-link',
  'blank',
  'checked',
  'current',
  'default',
  'defined',
  'disabled',
  'drop',
  'empty',
  'enabled',
  'first',
  'first-child',
  'first-of-type',
  'fullscreen',
  'future',
  'focus',
  'focus-visible',
  'focus-within',
  'host',
  'hover',
  'indeterminate',
  'in-range',
  'invalid',
  'last-child',
  'last-of-type',
  'left',
  'link',
  'local-link',
  'only-child',
  'only-of-type',
  'optional',
  'out-of-range',
  'past',
  'placeholder-shown',
  'read-only',
  'read-write',
  'required',
  'right',
  'root',
  'scope',
  'target',
  'target-within',
  'user-invalid',
  'valid',
  'visited',
]

export const GAP_LIST = ['unset', 'initial', 'inherit', 'normal']

export const VERTICAL_ALIGN_LIST = [
  'baseline',
  'sub',
  'super',
  'text-top',
  'text-bottom',
  'middle',
  'top',
  'bottom',
  'inherit',
  'initial',
  'unset',
]

export const BASE_MEDIA_QUERY = {
  sm: '(min-width: 640px)',
  md: '(min-width: 768px)',
  lg: '(min-width: 1024px)',
  xl: '(min-width: 1280px)',
}

export const BASE_MEDIA_QUERY_KEY = Object.keys(BASE_MEDIA_QUERY)
export const NONNEGATIVE_NUMBER_REGEX_STR = '(0|([1-9]\\d*))(\\.\\d*[1-9])?'
