name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2.0.1
      #   with:
      #     version: 6.15.1

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: v16
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - run: npx conventional-github-releaser -p angular
        continue-on-error: true
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.PROJECT_GITHUB_TOKEN}}

      - name: Install Dependencies
        run: npx ni

      - name: PNPM build
        run: npx nr build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
